---
title: "Cryptography lecture notes"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  bookdown::pdf_book: default
---

# (PART) Introduction to modern cryptography {-} 

# Front page {-}

*Latest update: 05/02/2021.*

This page contains some useful information related to the course and the lecture notes. Note that there are some useful buttons above the text, in particular one to download the notes as a well-formatted PDF, for offline use. 

#### Prerequisites {-}

The course assumes that you are familiar with previous maths courses from your degree. In particular, we will be using concepts from Probability theory and Discrete mathematics, and make extensive use of modular arithmetic. Refreshers for these topics can be found in Appendix \@ref(refreshers) and Section \@ref(modular-arithmetic).

#### Exercises {-}

Besides the exercise lists that you will have for practices or seminars, these notes also have some exercises embedded into the explanations. These are mostly easy exercises, designed to be a sort of 'sanity check' before moving to the next topic. Hence, our recommendation is that you stop and think about every exercise you encounter in these notes, instead of rushing through the content. You might not always be able to write a full and formal solution, but make sure to get at least an intuition on each exercise before moving on. 

#### SageMath {-}

*SageMath* (often called just *Sage*) is a powerful computer algebra system that we will use during the course to illustrate many concepts. It follows the Python syntax, which you will be familiar with, and comes equipped with many functions that are useful for cryptography. 

These notes will sometimes provide chunks of Sage code, so that you can play with some of the schemes that we will introduce. You are also encouraged to try and implement other schemes, or use Sage to double-check your solutions to exercises. 

There are two ways that you can use Sage:

-   Download it from <https://www.sagemath.org/download.html>. This will allow you to run SageMath locally. It also comes packaged with a Jupyter-style notebook, for ease of use.
-   Use it online at <https://cocalc.com/app>. This also comes in both terminal and notebook flavors. CoCalc has a freemium model, and in the free version you will get an annoying message telling you that your code will run really slow. Nevertheless, the free version is more than enough for the purpose of this course. 

The documentation at <https://doc.sagemath.org/> is pretty good, although most of the functions that we will use are self-explanatory. 

#### Bibliography {-}

1. Boaz Barak. An Intensive Introduction to Cryptography. *Available freely from* <https://intensecrypto.org/public/>.

2. Richard Crandall and Carl B Pomerance. *Prime numbers: a computational perspective*, volume 182. Springer Science & Business Media, 2006.

3. Jonathan Katz and Yehuda Lindell. *Introduction to modern cryptography*. CRC press, 2020.

(ref:paar) Christof Paar and Jan Pelzl. *Understanding cryptography: a textbook for students and practitioners*. Springer Science & Business Media, 2009.

4. (ref:paar)

5. Mike Rosulek. The Joy of Cryptography, 2017. Available freely from <http://web.engr.oregonstate.edu/~rosulekm/crypto>.

#### Changelog {-}

-   05/02/2021. Section \@ref(public-key-encryption) and Appendix \@ref(primality-testing) added. Minor fixes in Section \@ref(algebraic-structures). CRT moved to Section \@ref(elementary-number-theory).
-   26/01/2021. Section \@ref(algebraic-structures) and Appendices \@ref(ring-theory) and \@ref(polydiv) added.
-   21/01/2021. Minor fixes and additions in Sections \@ref(hash-functions) and \@ref(elementary-number-theory).
-   18/01/2021. Remainder of Section \@ref(elementary-number-theory) uploaded. Some typos fixed in Sections \@ref(block-ciphers) and \@ref(hash-functions).
-   13/01/2021. Section \@ref(hash-functions) uploaded. 
-   08/01/2021. Section \@ref(block-ciphers) uploaded. 
-   07/01/2021. Section \@ref(modular-arithmetic) and refreshers in Appendix \@ref(refreshers) added. Added code for LFSR. Some typos fixed in Sections \@ref(introduction-to-security) and \@ref(randomness-in-cryptography).
-   04/01/2021. Sections \@ref(introduction-to-security) and \@ref(randomness-in-cryptography) uploaded.



Notes written by Javier Silva, using [Bookdown](https://bookdown.org/) and [pandoc](https://pandoc.org/). 
